//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NumberStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumberStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NumberStrings", typeof(NumberStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string CompundDelimiter {
            get {
                return ResourceManager.GetString("CompundDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight.
        /// </summary>
        public static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighteen.
        /// </summary>
        public static string Eighteen {
            get {
                return ResourceManager.GetString("Eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighty.
        /// </summary>
        public static string Eighty {
            get {
                return ResourceManager.GetString("Eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleven.
        /// </summary>
        public static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifteen.
        /// </summary>
        public static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifty.
        /// </summary>
        public static string Fifty {
            get {
                return ResourceManager.GetString("Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        public static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forty.
        /// </summary>
        public static string Forty {
            get {
                return ResourceManager.GetString("Forty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        public static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourteen.
        /// </summary>
        public static string Fourteen {
            get {
                return ResourceManager.GetString("Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundred.
        /// </summary>
        public static string Hundred {
            get {
                return ResourceManager.GetString("Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million.
        /// </summary>
        public static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine.
        /// </summary>
        public static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nineteen.
        /// </summary>
        public static string Nineteen {
            get {
                return ResourceManager.GetString("Nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninety.
        /// </summary>
        public static string Ninety {
            get {
                return ResourceManager.GetString("Ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        public static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventeen.
        /// </summary>
        public static string Seventeen {
            get {
                return ResourceManager.GetString("Seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventy.
        /// </summary>
        public static string Seventy {
            get {
                return ResourceManager.GetString("Seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        public static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixteen.
        /// </summary>
        public static string Sixteen {
            get {
                return ResourceManager.GetString("Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixty.
        /// </summary>
        public static string Sixty {
            get {
                return ResourceManager.GetString("Sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirteen.
        /// </summary>
        public static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirty.
        /// </summary>
        public static string Thirty {
            get {
                return ResourceManager.GetString("Thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousand.
        /// </summary>
        public static string Thousand {
            get {
                return ResourceManager.GetString("Thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve.
        /// </summary>
        public static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty.
        /// </summary>
        public static string Twenty {
            get {
                return ResourceManager.GetString("Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
